version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: devscan_postgres
    restart: always
    environment:
      POSTGRES_USER: devscan
      POSTGRES_PASSWORD: devscan
      POSTGRES_DB: devscan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
